version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: tmmp-postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tmmp
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tmmp" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tmmp-network

volumes:
  postgres_data:

networks:
  tmmp-network:
    driver: bridge
