[versions]
mapstruct = "1.6.3"
lombok = "1.18.42"
postgresql = "42.7.10"
liquibase = "5.0.1"
springdoc = "3.0.1"
test-containers-postgresql = "1.21.4"
slf4j = "2.0.17"
junitAssert = '5.1.0'

[libraries]
# spring
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-jooq = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-boot-starter-liquibase = { module = "org.springframework.boot:spring-boot-starter-liquibase" }
spring-boot-starter-jooq-test = { module = "org.springframework.boot:spring-boot-starter-jooq-test" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aspectj" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-json = { module = "org.springframework.boot:spring-boot-starter-json" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }

# security

# database
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }

# documentation
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# utilities
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# test
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "test-containers-postgresql" }
json-unit-assert = { module = "net.javacrumbs.json-unit:json-unit-assertj", version.ref = "junitAssert" }

[bundles]
spring-web = [
    "spring-boot-starter-web",
    "spring-boot-starter-validation"
]

spring-data-jdbc = [
    "spring-boot-starter-jdbc",
    "spring-boot-starter-jooq"
]
